### ISSUE TITLE
Broken Image in submit project dialog box

### ISSUE THREAD

**Issue by Ansub** [dubinc/oss-gallery#7]
there is a cracked Image in `Submit a new project` dialog box

![CleanShot 2024-04-26 at 18 00 12@2x](https://github.com/dubinc/oss-gallery/assets/12985873/e432fcd2-c3fc-4195-a787-5f72a14895b7)

**Comment by steven-tey** [comment]
thanks for the report – sorry missed your PR before I committed to main 😅

**Comment by Ansub** [comment]
No worries Steven, Important thing is that the bug is fixed ✨
